urls.py
from django.conf.urls.defaults import *
from django.contrib import auth
from django.conf import settings
from phutaba.chan.models import BoardCategory
from phutaba.cms.models import News
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('django.contrib.auth.views',
	url(r'^accounts/login/$', 'login', {'template_name': 'core/login.html'}, name="login"),
	url(r'^accounts/logout/$', 'logout', {'template_name': 'core/logout.html'}, name="logout"),
	url(r'^accounts/pwchange/$', 'password_change', {'template_name': 'core/pwchange.html','post_change_redirect': '/accounts/pwchange/done/',}, name="pwchange"),
	url(r'^accounts/pwchange/done/$', 'password_change_done', {'template_name': 'core/pwchange_done.html'}, name="pwchange-done"),
	url(r'^accounts/pwreset/$', 'password_reset', {'template_name': 'core/pwreset.html','post_reset_redirect': '/accounts/pwreset/done/',}, name="pwreset"),
	url(r'^accounts/pwreset/done/$', 'password_reset_done', {'template_name': 'core/pwreset_done.html'}, name="pwreset-done"),
	url(r'^accounts/pwreset/confirm/(?P<token>(.+))/(?P<uidb36>(.+))/$', 'password_reset_confirm', {'template_name': 'core/pwreset_confirm.html'}, name="pwreset-confirm"),
	url(r'^accounts/pwreset/complete/$', 'password_reset_complete', {'template_name': 'core/pwreset_complete.html'}, name="pwreset-complete"),
)

urlpatterns += patterns('phutaba.cms.views',

	url(r'^$', 'static_view', {'template': 'cms/index.html', 'boardcategory_items': BoardCategory.objects.all(), 'news_items': News.objects.filter(published=True)[:5]}, name='start'),

	url(r'^rules/$', 'static_view', {'template': 'rules.html',}, name='rules'),
	url(r'^faq/$', 'static_view', {'template': 'faq.html',}, name='faq'),
	url(r'^irc/$', 'static_view', {'template': 'irc.html',}, name='irc'),

	url(r'^cms/(?P<page>(.*))/$', 'dynamic_view', name='dynamic'),
	
	url(r'^robots.txt$', 'static_view', {'template': 'robots.txt',}, name='robots'),
)

urlpatterns += patterns('phutaba.chan.views',
		
	url(r'^(?P<board>(\w{1,4}))/$', 'board_view', name='board'),
	url(r'^(?P<board>(\w{1,4}))/post/$', 'post_view', name='board-post'),
	url(r'^(?P<board>(\w{1,4}))/(?P<thread_id>(\d+))/$', 'thread_view', name='thread'),
	url(r'^(?P<board>(\w{1,4}))/(?P<thread_id>(\d+))/post/$', 'post_view', name='thread-post'),
#	url(r'^(?P<board>(\w{1,4}))/(?P<thread_id>(\d+))/(?P<file>(\w+\.\w{3,4}))/$', 'thread_file_view', name='thread-file'),
	
	url(r'^_ajax/postinfo/(?P<post_id>(\d+))/$', 'ajax_postinfo_view', name='ajax-postinfo'),
	url(r'^_ajax/postaction/(?P<post_id>(\d+))/$', 'ajax_postaction_view', name='ajax-postaction'),
	
	url(r'^(?P<board>(\w{1,4}))/(?P<thread_id>(\d+))/lock/$', 'thread_lock_view', name='thread-lock'),
	url(r'^(?P<board>(\w{1,4}))/(?P<thread_id>(\d+))/sticky/$', 'thread_sticky_view', name='thread-sticky'),
	url(r'^(?P<board>(\w{1,4}))/(?P<thread_id>(\d+))/autosage/$', 'thread_autosage_view', name='thread-autosage'),
	url(r'^(?P<board>(\w{1,4}))/(?P<thread_id>(\d+))/(?P<post_id>(\d+))/delete/$', 'post_delete_view', name='post-delete'),

)

urlpatterns += patterns('',
	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False }),
	(r'^admin/', include(admin.site.urls)),
)

chan/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.db.models import Q, Count, Sum
from django.db.models.fields import IntegerField

class BigIntegerField(IntegerField):
	empty_strings_allowed=False
	def get_internal_type(self):
		return "BigIntegerField"
	def db_type(self):
		return 'bigint' # Note this won't work with Oracle.


class UserProfile(models.Model):
	user = models.ForeignKey(User, unique=True)
	level = models.PositiveSmallIntegerField(default=1)
	
	def __unicode__(self):
		return "UserProfile of %s" % self.user.username

class UserACL(models.Model):
	user = models.ForeignKey(User)
	board = models.ForeignKey('Board')
	perm_view_post_data = models.BooleanField(default=False)
	perm_post_as_mod = models.BooleanField(default=False)
	perm_no_captchas = models.BooleanField(default=False)
	perm_delete = models.BooleanField(default=False)
	perm_sticky = models.BooleanField(default=False)
	perm_close = models.BooleanField(default=False)
	perm_ban = models.BooleanField(default=False)
	perm_evade_ban = models.BooleanField(default=False)
	
	def __unicode__(self):
		return "UserACL for %s on %s" % (self.user.username, self.board)

class BoardCategory(models.Model):
	name = models.CharField(max_length=255)
	nsfw = models.BooleanField()
	order = models.SmallIntegerField() # high = up

	def __unicode__(self):
		return "%s%s" % (self.name, ('',' (NSFW)')[self.nsfw])

	class Meta:
		ordering = ['-order','id']

class Board(models.Model):
	identifier = models.CharField(max_length=10, unique=True)
	category = models.ForeignKey(BoardCategory)
	title = models.CharField(max_length=255)
	subtitle = models.CharField(max_length=255)
	allow_uploads = models.BooleanField(default=True)
	pages = models.PositiveSmallIntegerField(default=10)
	force_nick = models.BooleanField(default=False)
	default_nick = models.CharField(max_length=50)
	sage_limit = models.PositiveIntegerField(default=50)
	sage_string = models.CharField(max_length=30, default="SAGE!")
	autosage_string = models.CharField(max_length=30, default="AUTOSAGE")
	ban_string = models.CharField(max_length=255, default="USER WAS BANNED FOR THIS POST")
	mod_string = models.CharField(max_length=30, default="STAFF")
	
	def __unicode__(self):
		return "/%s/ - %s" % (self.identifier, self.title)
	
	class Meta:
		ordering = ["category", "identifier"]

class Thread(models.Model):
	board = models.ForeignKey(Board)
	time_created = models.DateTimeField(null=False, blank=False)
	is_locked = models.BooleanField(default=False)
	is_sticky = models.BooleanField(default=False)
	flag_autosage = models.BooleanField(default=False)
	cached_last_post = models.DateTimeField(null=False, blank=False)
	
	@property
	def first_post(self):
		try:
			p = Post.objects.filter(thread=self).order_by('time','localpk')[0]
			return p
		except:
			return False
	
	@property
	def last_post(self):
		try:
			p = Post.objects.filter(thread=self).order_by('-time','-localpk')[0]
			return p
		except:
			return False
	
	@property
	def sagecount(self):
		try:
			p = Post.objects.filter(thread=self, flag_sage=True).count()
			return p
		except:
			return 0
	
	def save(self): # update cached_last_post automatically
		if self.last_post and not self.flag_autosage:
			self.cached_last_post = self.last_post.time 
		super(Thread, self).save()
	
	def delete(self):
		for p in self.post_set.all():
			try:
				p.delete()
			except:
				pass
		super(Thread, self).delete()
		
	class Meta:
		ordering = ['-is_sticky', '-cached_last_post']

class Post(models.Model):
#	board = models.ForeignKey(Board)
	thread = models.ForeignKey(Thread)
	localpk = models.PositiveIntegerField(null=False, blank=False)
	time = models.DateTimeField(null=False, blank=False)
	title = models.CharField(max_length=255, null=True, blank=True)
	nick = models.CharField(max_length=255, null=True, blank=True)
	ip = models.IPAddressField(null=False, blank=False)
	host = models.CharField(max_length=255, null=True, blank=True)
	location = models.CharField(max_length=255, null=True, blank=True)
	useragent = models.CharField(max_length=255, null=True, blank=True)
	content = models.TextField(max_length=5000)
	content_HTML = models.TextField(max_length=7000)
	password = models.CharField(max_length=50, null=True, blank=True)
	flag_sage = models.BooleanField(default=False)
	flag_op = models.BooleanField(default=False)
	flag_banned = models.BooleanField(default=False)
	flag_hidden = models.BooleanField(default=False)
	flag_reported = models.BooleanField(default=False)
	flag_verified = models.BooleanField(default=False)
	custom_banned = models.CharField(max_length=255, null=True, blank=True)
	user = models.ForeignKey(User, blank=True, null=True)
	rank = models.CharField(max_length=255, null=True, blank=True)
	#files = models.ManyToManyField('File')
	
	def delete(self): # update cached_last_post automatically
		for f in self.postfile_set.all():
			try:
				f.delete()
			except:
				pass
		super(Post, self).delete()
		self.thread.save()
	
	def save(self): # update cached_last_post automatically
		super(Post, self).save()
		if self.flag_sage and not self.thread.flag_autosage:
			if Post.objects.filter(thread=self.thread).count() >= self.thread.board.sage_limit:
				self.thread.flag_autosage = True
				self.thread.save()
				return True
		if not self.flag_sage and not self.thread.flag_autosage:
			self.thread.save()
	class Meta:
		ordering = ['localpk','time']
	
class PostFile(models.Model):
	post = models.ForeignKey(Post)
	filetype = models.CharField(max_length=100) # (data|image)
	original_name = models.CharField(max_length=255)
	fileid = BigIntegerField()
	filesize = models.CharField(max_length=100, null=True, blank=True)
	data = models.FileField(upload_to="uploads/files/", null=True, blank=True) #XXX
	image = models.ImageField(upload_to="uploads/images/", null=True, blank=True) #XXX
	imagethumb = models.ImageField(upload_to="uploads/images/thumbs/", null=True, blank=True)
	imagedimensions = models.CharField(max_length=255, null=True, blank=True)
 
class Wordfilter(models.Model):
	boards = models.ManyToManyField(Board)
	filter = models.CharField(max_length=255)
	value = models.TextField()

	def __unicode__(self):
		return "%s => %s" % (self.filter, self.value[:100])
 
class Ban(models.Model):
	ip = models.CharField(max_length=255) # IPAddressFields are not ipv6 ready yet.
	netmask = models.PositiveSmallIntegerField(default=32)
	admin = models.ForeignKey(User)
	boards = models.ManyToManyField(Board, null=True) # if null, it's a global ban
	time_set = models.DateTimeField(null=False, blank=False)
	time_expiration = models.DateTimeField(null=True, blank=True)
	reason = models.CharField(max_length=255)
	appeal = models.CharField(max_length=1000, null=True, blank=True)
	appeal_allow = models.BooleanField(default=False)
	appeal_void = models.BooleanField(default=False)
	
	def __unicode__(self):
		return "%s/%d" % (self.ip, self.netmask)

class Whitelist(models.Model):
	ip = models.CharField(max_length=255)
	code = models.CharField(max_length=255)
	time_set = models.DateTimeField(null=False, blank=False)
	time_expiration = models.DateTimeField(null=True, blank=True)
	issuer = models.ForeignKey(User)

	def __unicode__(self):
		return "%s (%s)" % (self.code, self.ip)

cms/models.py
from django.db import models
from django.contrib.auth.models import User

class Page(models.Model):
	url = models.CharField(max_length=255)
	name = models.CharField(max_length=255)
	base_template = models.CharField(max_length=255)

	@property
	def content(self):
		try:
			return self.pagerevision_set.filter(published=True)[:1][0]
		except:
			raise # XXX
	
	def __unicode__(self):
		return "%s/ (%s)" % (self.url, self.name)

class PageRevision(models.Model):
	page = models.ForeignKey(Page)
	user = models.ForeignKey(User)
	time = models.DateTimeField(null=False, blank=False)
	content_HTML = models.TextField()
	published = models.BooleanField(default=False)

	def __unicode__(self):
		return "%s r%d (by %s, %s)" % (self.page, self.pk, self.user.username, self.time)

	class Meta:
		ordering = ['-time']

class News(models.Model):
	user = models.ForeignKey(User)
	time = models.DateTimeField(null=False, blank=False)
	title = models.CharField(max_length=255, null=True, blank=True)
	content = models.TextField(max_length=5000)
	content_HTML = models.TextField(max_length=7000)
	published = models.BooleanField(default=False)

	def __unicode__(self):
		return "\"%s\" by %s, %s" % (self.title, self.user.username, self.time)
	class Meta:
		ordering = ['-time']

cms/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.http import Http404, HttpResponseServerError, HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.template import RequestContext
from django.contrib import messages
from django.db.models import Q, Sum, Count
from django.core.urlresolvers import reverse
import datetime, os, socket
from phutaba.settings import APP_URL, MEDIA_ROOT, VALID_IMAGE_EXTENSIONS, VALID_IMAGE_MIME, VALID_FILE_EXTENSIONS, VALID_FILE_MIME
from dateutil import relativedelta
from phutaba.cms.models import *
import re
from django.core.files import File
from django.core.files.base import ContentFile
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.template.defaultfilters import slugify
try:
    import cStringIO as StringIO
except ImportError:
    import StringIO

def static_view(request, template, **args):	
	return render_to_response(template, locals(), context_instance=RequestContext(request))

def dynamic_view(request, page, **args):
	mypage = get_object_or_404(Page, url=page)
	return render_to_response("cms/%s" % mypage.base_template, locals(), context_instance=RequestContext(request))

templates/cms/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

<head>

 <title>Ernstchan - {% block title %}powered by Phutaba{% endblock %}</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
 <link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/static.css" />
 <link rel="shortcut icon" href="{{MEDIA_URL}}favicon.ico" />
 
</head>

<body >

 <div class="menu">
  <a href="newfaq.html">FAQ</a>
  <a href="newrules.html">Regeln</a>
  <a href="irc://irc.euirc.net/ernstchan" title="#ernstchan @ euIRC">IRC-Channel</a>
  <a href="/s/">Support</a>
  <a href="newdonate.html">Spenden</a>
 </div>

 <div class="name"><a href="newindex.html">Ernstchan</a></div>
 <div class="slogan">&bdquo;zuf&auml;lliger Slogan&ldquo;</div>
 
 <hr />
 
 {% block content %}{% endblock %}

 
 <hr />
 
 <div class="footer_left">&copy; 2010-2011 Ernstchan</div>
 <div class="footer_right"><img src="img/phutaba.png" alt="Phutaba" title="Version 3.0" /></div>
 
</body>

</html> 

templates/cms/dynamic.html
{% extends "cms/base.html" %}

{% block title %}{{ mypage.name }}{% endblock %}

{% block content %}
	 <div class="caption">{{ mypage.name }}</div>

	 {{ mypage.content.content_HTML|safe }}
{% endblock %}

templates/cms/index.html
{% extends "cms/base.html" %}
{% load cms %}

{% block content %} 
 <div class="boards">
 
  <div class="caption">Boards</div>
  
  <div class="item">
   <div class="title">
    Suchfunktion
   </div>
   <div class="content">
    <form class="search">
     <input type="text" value="" />
     <input type="submit" value="Suchen" />
    </form>
   </div>
  </div>

{% for cat in args.boardcategory_items %}
  <div class="item">
   <div class="title">
    {{ cat }}
   </div>
   {% for board in cat.board_set.all %}
   <div class="content">
    <ul>
      <li>
        <a href="/{{ board.identifier }}/">
          <strong>/{{ board.identifier }}/</strong> {{ board.title }}
        </a>
      </li>
    </ul>
   </div>
   {% endfor %}
  </div>
{% endfor %}
 </div>

 
 <div class="news">
 
 <div class="caption">News</div>
 
{% for news in args.news_items %}
  <div class="item">
   <div class="title">
    {{news.title}} &mdash; {{news.user}} &mdash; {{news.time|date:"d.m.Y H:i"}}
   </div>
   <div class="content">
    {{news.content_HTML|safe}}
   </div>
  </div>
{% endfor %}
 </div>

{% endblock %}

templates/cms/new403.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

<head>

 <title>Ernstchan - Error 403</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
 <link rel="stylesheet" type="text/css" href="css/static.css" />
 <link rel="shortcut icon" href="favicon.ico" />

</head>

<body >

 <div class="menu">
  <a href="newfaq.html">FAQ</a>
  <a href="newrules.html">Regeln</a>
  <a href="irc://irc.euirc.net/ernstchan" title="#ernstchan @ euIRC">IRC-Channel</a>
  <a href="/s/">Support</a>
  <a href="newdonate.html">Spenden</a>
 </div>

 <div class="name"><a href="newindex.html">Ernstchan</a></div>
 <div class="slogan">&bdquo;zuf&auml;lliger Slogan&ldquo;</div>
 
 <hr />
 
 <span class="error">
  <div class="caption"><img src="/img/403.png" alt="403" /><br />Error 403 - Zugriff verweigert</div>
  <p>Du hast nicht die Rechte, auf die gew&uuml;nschte Seite zuzugreifen.</p>
 </span>
 
 <hr />
 
 <div class="footer_left">&copy; 2010-2011 Ernstchan</div>
 <div class="footer_right"><img src="img/phutaba.png" alt="Phutaba" title="Version 3.0" /></div>
 
</body>

</html> 

templates/cms/new404.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

<head>

 <title>Ernstchan - Error 404</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
 <link rel="stylesheet" type="text/css" href="css/static.css" />
 <link rel="shortcut icon" href="favicon.ico" />

</head>

<body >

 <div class="menu">
  <a href="newfaq.html">FAQ</a>
  <a href="newrules.html">Regeln</a>
  <a href="irc://irc.euirc.net/ernstchan" title="#ernstchan @ euIRC">IRC-Channel</a>
  <a href="/s/">Support</a>
  <a href="newdonate.html">Spenden</a>
 </div>

 <div class="name"><a href="newindex.html">Ernstchan</a></div>
 <div class="slogan">&bdquo;zuf&auml;lliger Slogan&ldquo;</div>
 
 <hr />
 
 <span class="error">
  <div class="caption"><img src="/img/404.png" alt="404" /><br />Error 404 - Objekt nicht gefunden</div>
  <p>Die gew&uuml;nschte Datei existiert nicht oder wurde bereits gel&ouml;scht.</p>
 </span>
 
 <hr />
 
 <div class="footer_left">&copy; 2010-2011 Ernstchan</div>
 <div class="footer_right"><img src="img/phutaba.png" alt="Phutaba" title="Version 3.0" /></div>
 
</body>

</html> 

templates/cms/newbanned.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

<head>

 <title>Ernstchan - Zugriff blockiert</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
 <link rel="stylesheet" type="text/css" href="css/static.css" />
 <link rel="shortcut icon" href="favicon.ico" />

</head>

<body >

 <div class="menu">
  <a href="newfaq.html">FAQ</a>
  <a href="newrules.html">Regeln</a>
  <a href="irc://irc.euirc.net/ernstchan" title="#ernstchan @ euIRC">IRC-Channel</a>
  <a href="/s/">Support</a>
  <a href="newdonate.html">Spenden</a>
 </div>

 <div class="name"><a href="newindex.html">Ernstchan</a></div>
 <div class="slogan">&bdquo;zuf&auml;lliger Slogan&ldquo;</div>
 
 <hr />
 
 <div class="caption">Zugriff blockiert</div>
 
 <div class="item">
  <div class="title">
   Deine IP-Adresse (127.0.0.1) wurde gebannt.
  </div>
  <div class="content">
   <p><strong>Angegebener Grund:</strong><br /><em>CP - fick dich wek du hurren son</em></p>
   <p>Du bist seit dem <strong>2.10.2010 um 13:37 Uhr</strong> gesperrt und wirst am <strong>16.10.2010 um 13:37 Uhr</strong> wieder freigeschaltet.<br />Bis dahin hast <span class="green_sign">&#10004;</span> <span class="green">Leserechte</span> und <span class="red_sign">&#10006;</span> <span class="red">keine Schreibrechte</span>.</p>
   Solltest du einen plausiblen Grund daf&uuml;r haben, die Sperre zu entfernen, so kontaktiere den zust&auml;ndigen Moderator (Weissbier) im <a href="irc://irc.euirc.net/ernstchan">IRC</a>.
  </div>
 </div>
 
 <hr />
 
 <div class="footer_left">&copy; 2010-2011 Ernstchan</div>
 <div class="footer_right"><img src="img/phutaba.png" alt="Phutaba" title="Version 3.0" /></div>

</body>

</html> 

templates/cms/newdonate.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

<head>

 <title>Ernstchan - Spenden</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
 <link rel="stylesheet" type="text/css" href="css/static.css" />
 <link rel="shortcut icon" href="favicon.ico" />
 
</head>

<body >

 <div class="menu">
  <a href="newfaq.html">FAQ</a>
  <a href="newrules.html">Regeln</a>
  <a href="irc://irc.euirc.net/ernstchan" title="#ernstchan @ euIRC">IRC-Channel</a>
  <a href="/s/">Support</a>
  <a href="newdonate.html">Spenden</a>
 </div>

 <div class="name"><a href="newindex.html">Ernstchan</a></div>
 <div class="slogan">&bdquo;zuf&auml;lliger Slogan&ldquo;</div>
 
 <hr />
 
 <div class="caption">Spenden</div>
 
 <div class="item">
  <div class="title">
   &euro;&euro;&euro;
  </div>
  <div class="content">
   Jede Spende hilft dabei, unseren Server zu finanzieren. Da wir viel Wert auf eure und auch unsere Anonymit&auml;t legen, gibt es nur zwei Möglichkeiten, uns Geld zukommen zu lassen.
   <ol>
    <li>Ihr klickt auf unseren Tumblr-Button: <br /><script type="text/javascript"> var flattr_url = 'http://ernstchan.net'; var flattr_btn='compact';</script><script src="http://api.flattr.com/button/load.js" type="text/javascript"></script></li>
    <li>Ihr kauft euch eine <a href="http://www.paysafecard.com/de/kaufen/verkaufsstellen/">paysafecard</a> und lasst uns per <a href="http://www.google.com/recaptcha/mailhide/d?k=01bimScZkDomRfgjrHHc3Yjw==&amp;c=XWz9HZaiON1FNPBGx71T2XHhOdNJCLPYbMGYFy9he-8=" onclick="window.open('http://www.google.com/recaptcha/mailhide/d?k\07501bimScZkDomRfgjrHHc3Yjw\75\75\46c\75XWz9HZaiON1FNPBGx71T2XHhOdNJCLPYbMGYFy9he-8\075', '', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=300'); return false;">E-Mail</a> den PIN-Code zukommen.</li>
   </ol>
   Falls ihr &uuml;brigens eine weitere Möglichkeit kennt, komplett anonym Geld zu verschicken und empfangen, dann lasst uns das wissen.
  </div>
 </div>
 
 <hr />
 
 <div class="footer_left">&copy; 2010-2011 Ernstchan</div>
 <div class="footer_right"><img src="img/phutaba.png" alt="Phutaba" title="Version 3.0" /></div>
 
</body>

</html> 

templates/cms/newerror.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

<head>

 <title>Ernstchan - Phutaba Error</title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
 <link rel="stylesheet" type="text/css" href="css/static.css" />
 <link rel="shortcut icon" href="favicon.ico" />

</head>

<body >

 <div class="menu">
  <a href="newfaq.html">FAQ</a>
  <a href="newrules.html">Regeln</a>
  <a href="irc://irc.euirc.net/ernstchan" title="#ernstchan @ euIRC">IRC-Channel</a>
  <a href="/s/">Support</a>
  <a href="newdonate.html">Spenden</a>
 </div>

 <div class="name"><a href="newindex.html">Ernstchan</a></div>
 <div class="slogan">&bdquo;zuf&auml;lliger Slogan&ldquo;</div>
 
 <hr />
 
 <span class="error">
  <div class="caption">Phutaba Error</div>
  <p class="error_msg">hurrdurr herpderp at line 9001</p>
 </span>
 
 <hr />
 
 <div class="footer_left">&copy; 2010-2011 Ernstchan</div>
 <div class="footer_right"><img src="img/phutaba.png" alt="Phutaba" title="Version 3.0" /></div>
 
</body>

</html> 